/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package bitsexcel.pos.JavaPosProject;

import be.odoo.frm.PedidosOdoo;
import be.pos.PosForm;
import be.pos.panels.ActividadEconomicaPnl;
import be.pos.panels.BuscarDocumentosMH;
import be.pos.panels.CorreoPnl;
import be.pos.panels.FirmaPnl;
import be.pos.panels.IdpPnl;
import be.pos.panels.TokenPnl;
import javax.swing.JFrame;

/**
 *
 * @author jdaniel
 */
public class NewMDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    public NewMDIApplication() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        internalIdp = new javax.swing.JInternalFrame();
        internalToken = new javax.swing.JInternalFrame();
        internalCorreo = new javax.swing.JInternalFrame();
        internalFirma = new javax.swing.JInternalFrame();
        internalUltimosDoc = new javax.swing.JInternalFrame();
        internalActividadEco = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1000, 650));

        internalIdp.setClosable(true);
        internalIdp.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        internalIdp.setResizable(true);
        internalIdp.setNormalBounds(new java.awt.Rectangle(40, 10, 550, 350));
        internalIdp.setPreferredSize(new java.awt.Dimension(490, 390));
        internalIdp.setVisible(false);

        javax.swing.GroupLayout internalIdpLayout = new javax.swing.GroupLayout(internalIdp.getContentPane());
        internalIdp.getContentPane().setLayout(internalIdpLayout);
        internalIdpLayout.setHorizontalGroup(
            internalIdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        internalIdpLayout.setVerticalGroup(
            internalIdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        desktopPane.add(internalIdp);
        internalIdp.setBounds(40, 10, 490, 390);

        internalToken.setClosable(true);
        internalToken.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        internalToken.setPreferredSize(new java.awt.Dimension(450, 350));
        internalToken.setVisible(false);

        javax.swing.GroupLayout internalTokenLayout = new javax.swing.GroupLayout(internalToken.getContentPane());
        internalToken.getContentPane().setLayout(internalTokenLayout);
        internalTokenLayout.setHorizontalGroup(
            internalTokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        internalTokenLayout.setVerticalGroup(
            internalTokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        desktopPane.add(internalToken);
        internalToken.setBounds(60, 40, 450, 350);

        internalCorreo.setClosable(true);
        internalCorreo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        internalCorreo.setPreferredSize(new java.awt.Dimension(450, 350));
        internalCorreo.setVisible(false);

        javax.swing.GroupLayout internalCorreoLayout = new javax.swing.GroupLayout(internalCorreo.getContentPane());
        internalCorreo.getContentPane().setLayout(internalCorreoLayout);
        internalCorreoLayout.setHorizontalGroup(
            internalCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        internalCorreoLayout.setVerticalGroup(
            internalCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(internalCorreo);
        internalCorreo.setBounds(60, 40, 450, 350);

        internalFirma.setClosable(true);
        internalFirma.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        internalFirma.setPreferredSize(new java.awt.Dimension(450, 350));
        internalFirma.setVisible(false);

        javax.swing.GroupLayout internalFirmaLayout = new javax.swing.GroupLayout(internalFirma.getContentPane());
        internalFirma.getContentPane().setLayout(internalFirmaLayout);
        internalFirmaLayout.setHorizontalGroup(
            internalFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        internalFirmaLayout.setVerticalGroup(
            internalFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(internalFirma);
        internalFirma.setBounds(60, 40, 450, 350);

        internalUltimosDoc.setClosable(true);
        internalUltimosDoc.setPreferredSize(new java.awt.Dimension(450, 360));
        internalUltimosDoc.setVisible(false);

        javax.swing.GroupLayout internalUltimosDocLayout = new javax.swing.GroupLayout(internalUltimosDoc.getContentPane());
        internalUltimosDoc.getContentPane().setLayout(internalUltimosDocLayout);
        internalUltimosDocLayout.setHorizontalGroup(
            internalUltimosDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        internalUltimosDocLayout.setVerticalGroup(
            internalUltimosDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(internalUltimosDoc);
        internalUltimosDoc.setBounds(60, 40, 450, 360);

        internalActividadEco.setClosable(true);
        internalActividadEco.setPreferredSize(new java.awt.Dimension(750, 500));
        internalActividadEco.setVisible(false);

        javax.swing.GroupLayout internalActividadEcoLayout = new javax.swing.GroupLayout(internalActividadEco.getContentPane());
        internalActividadEco.getContentPane().setLayout(internalActividadEcoLayout);
        internalActividadEcoLayout.setHorizontalGroup(
            internalActividadEcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        internalActividadEcoLayout.setVerticalGroup(
            internalActividadEcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(internalActividadEco);
        internalActividadEco.setBounds(30, 40, 750, 500);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("POS");

        jMenuItem6.setText("Tiquete");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Facturador");

        jMenuItem7.setText("odoo");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Configuracion");

        jMenuItem1.setText("act. economica");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("idp");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("token");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("firma");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("correo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem8.setText("ultimos doc");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu7.setText("Odoo");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        IdpPnl idp = new IdpPnl(internalIdp);
        internalIdp.setContentPane(idp);
        internalIdp.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
       
        TokenPnl tk = new TokenPnl(internalToken);
        internalToken.setContentPane(tk);
        internalToken.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    //CONFIGURACION FIRMA
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        
        FirmaPnl sig = new FirmaPnl(internalFirma);
        internalFirma.setContentPane(sig);
        internalFirma.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    //CONFIGURACION DE CORREO
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        CorreoPnl mail = new CorreoPnl(internalCorreo);
        internalCorreo.setContentPane(mail);
        internalCorreo.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         PosForm pos = new PosForm();
         pos.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
         pos.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        PedidosOdoo po = new PedidosOdoo();
        po.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        po.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        BuscarDocumentosMH bdmh = new BuscarDocumentosMH(internalUltimosDoc);
        internalUltimosDoc.setContentPane(bdmh);
        internalUltimosDoc.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ActividadEconomicaPnl ae = new ActividadEconomicaPnl(internalActividadEco);
        internalActividadEco.setContentPane(ae);
        internalActividadEco.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMDIApplication().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JInternalFrame internalActividadEco;
    private javax.swing.JInternalFrame internalCorreo;
    private javax.swing.JInternalFrame internalFirma;
    private javax.swing.JInternalFrame internalIdp;
    private javax.swing.JInternalFrame internalToken;
    private javax.swing.JInternalFrame internalUltimosDoc;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables

}
