/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.pos;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class JFrameVuelto extends javax.swing.JFrame {
    
    String totalString;
    double total;
    double efectivo;
    String efectivoString;
    double cambio;
    String cambioString;
//    PosForm pos;

    /**
     * Creates new form JFrameVuelto
     */
    public JFrameVuelto( ) {
//        public JFrameVuelto(PosForm pos ) { this.pos = pos;
        initComponents();
        
    }
    
    public void darVuelto(double total){
        this.total = total;
        totalString = String.format("%.02f",total);
        jLabelVuelto.setText(totalString);
        jTextFieldPago.requestFocus();
    }
    
    public void limpiarCampos(){
        
        jLabelVuelto3.setText("");
        jTextFieldPago.setText("");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelVuelto = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldPago = new javax.swing.JTextField();
        jLabelVuelto2 = new javax.swing.JLabel();
        jLabelVuelto3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelVuelto.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTotal.setText("TOTAL");

        jTextFieldPago.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextFieldPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPagoKeyReleased(evt);
            }
        });

        jLabelVuelto2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelVuelto2.setText("VUELTO");

        jLabelVuelto3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jTextFieldPago, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelVuelto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelVuelto3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jLabelVuelto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelVuelto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVuelto3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVuelto2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jTextFieldPago, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jTextFieldPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPagoKeyReleased
        // TODO add your handling code here:
        try{
        if(evt.getKeyCode() == evt.VK_ENTER){
            
            efectivoString = jTextFieldPago.getText();
            efectivo = Double.parseDouble(efectivoString);
            cambio = efectivo - total;
            cambioString = String.format("%.02f",cambio);
            jLabelVuelto3.setText(cambioString);
            jTextFieldPago.setText("");
//            pos.limpiarTabla();
            
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Ingrese Cantidad solo en numeros", "Error",JOptionPane.ERROR_MESSAGE);
        
        }
        
        
       
        
    }//GEN-LAST:event_jTextFieldPagoKeyReleased

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelVuelto;
    private javax.swing.JLabel jLabelVuelto2;
    private javax.swing.JLabel jLabelVuelto3;
    private javax.swing.JTextField jTextFieldPago;
    // End of variables declaration//GEN-END:variables
}
