/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.pos;

import be.pos.dat.ProductoDB;
import be.pos.dat.RendimientoDB;
import be.pos.ent.Producto;
import be.pos.ent.Rendimiento;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oficina
 */
public class PosForm extends javax.swing.JFrame {

    DefaultTableModel modelo;
    JFrameVuelto jfrmvuelto;
    FrameAgregar jfrmagregar;
    double suma_total;
    int registry_count;
    int int_copy;
    double double_copy;
    int ganancia;
    String cadena_total;
    ProductoDB productodb;
    Producto producto;
    RendimientoDB rendimientodb;
    Rendimiento rendimiento;
    String[] datos;
    String var_consulta;
    String str_copy;
    List<Producto> list_producto;

    public PosForm() {
        modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("nombre");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        initComponents();
        jfrmvuelto = new JFrameVuelto();
        jfrmvuelto.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        jfrmagregar = new FrameAgregar();
        jfrmagregar.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        suma_total = 0.0;
        registry_count = 0;
        int_copy = 0;
        double_copy = 0.0;
        ganancia = 0;
        str_copy = "";
        cadena_total = "";
        //var_consulta = "";
        datos = new String[4];
        //copy_datos = new String[4];
        productodb = new ProductoDB();
        producto = new Producto();
        rendimientodb = new RendimientoDB();
        rendimiento = new Rendimiento();

        list_producto = new ArrayList<Producto>();
        jTextFieldCod.requestFocus();
    }

    public void pagar() {
        list_producto = new ArrayList<Producto>();
        //rendimiento = new Rendimiento();
        if (rendimientodb.existencia()) {
            rendimientodb.actualizar(rendimiento);
        }
        if (!rendimientodb.existencia()) {
            rendimientodb.insertar(rendimiento);
        }
        while (modelo.getRowCount() > 0) {
            producto = new Producto();
            str_copy = modelo.getValueAt(0, 0).toString();
            producto.setId(str_copy);
            str_copy = modelo.getValueAt(0, 2).toString();
            int_copy = Integer.valueOf(str_copy);
            producto.setCantidad(int_copy);
            list_producto.add(producto);
            modelo.removeRow(0);
        }
        productodb.actualizarCantidad(list_producto);
        rendimiento = new Rendimiento();
        suma_total = 0.0;
        jTextFieldTot.setText("");
        jTextFieldCod.requestFocus();
    }

    public void nuevaVenta() {
        jfrmvuelto.darVuelto(suma_total);
        pagar();
        jfrmvuelto.limpiarCampos();
        jfrmvuelto.setVisible(true);
//        jfrmvuelto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jButtonAgr = new javax.swing.JButton();
        jButtonEli = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCan = new javax.swing.JTextField();
        jTextFieldTot = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_nueva_venta = new javax.swing.JButton();
        btnEliminarVenta = new javax.swing.JButton();
        jbtn_imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema no contable (RTS)");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cantidad");

        jTextFieldCod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });
        jTextFieldCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCodKeyReleased(evt);
            }
        });

        jButtonAgr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAgr.setText("Agregar");
        jButtonAgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgrActionPerformed(evt);
            }
        });

        jButtonEli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEli.setText("Eliminar");
        jButtonEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliActionPerformed(evt);
            }
        });

        jTablePos.setBackground(new java.awt.Color(0, 204, 204));
        jTablePos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTablePos.setModel(modelo);
        jTablePos.setRowHeight(30);
        jScrollPane1.setViewportView(jTablePos);
        jTablePos.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Codigo");

        jTextFieldCan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldCan.setText("1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Total  ");

        btn_nueva_venta.setBackground(new java.awt.Color(0, 204, 51));
        btn_nueva_venta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_nueva_venta.setText("Pagar");
        btn_nueva_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nueva_ventaActionPerformed(evt);
            }
        });

        btnEliminarVenta.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminarVenta.setText("Eliminar Venta");
        btnEliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVentaActionPerformed(evt);
            }
        });

        jbtn_imprimir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_imprimir.setText("Imprimir");
        jbtn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTot, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn_imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAgr)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                                .addComponent(btn_nueva_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAgr)
                    .addComponent(jButtonEli)
                    .addComponent(btn_nueva_venta)
                    .addComponent(jTextFieldCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_imprimir)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarVenta)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgrActionPerformed

        var_consulta = jTextFieldCod.getText();
        producto = new Producto();
        //rendimiento = new Rendimiento();
        if (jTextFieldCod.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Falta valor de Codigo");
        } else {
            try {

                producto = productodb.consultar(var_consulta);
                if (producto.getId() == "") {
                    JOptionPane.showMessageDialog(null, "Producto no registrado");
//                        jfrmagregar.setVisible(true);
                } else {
                    registry_count = modelo.getRowCount();
                    rendimiento.setIngreso(rendimiento.getIngreso() + (Integer.valueOf(jTextFieldCan.getText())) * producto.getGanancia());
                    rendimiento.setImpuesto(rendimiento.getImpuesto() + (Integer.valueOf(jTextFieldCan.getText())) *producto.getIva());
                    rendimiento.setVenta(rendimiento.getVenta() + (Integer.valueOf(jTextFieldCan.getText())) *producto.getPrecio());

                    datos[0] = producto.getId();
                    datos[1] = producto.getNombre();
                    datos[2] = jTextFieldCan.getText();

                    double_copy = Double.parseDouble(jTextFieldCan.getText()) * producto.getPrecio();
                    str_copy = String.format("%.02f",double_copy);
                    datos[3] = str_copy;
//                    modelo.addRow(datos);
                    modelo.insertRow(0,datos);
                    //cadena_total += Integer.toString(registry_count);
//                    cadena_total = modelo.getValueAt(registry_count, 3).toString();
                    cadena_total = modelo.getValueAt(0, 3).toString();
                    suma_total += Double.valueOf(cadena_total);
                    jTextFieldTot.setText(String.format("%.02f",suma_total));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error " + e);
            }
        }
        jTextFieldCod.setText("");
        jTextFieldCan.setText("1");
        jTextFieldCod.requestFocus();
    }//GEN-LAST:event_jButtonAgrActionPerformed

    private void jButtonEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliActionPerformed
        // TODO add your handling code here:
        producto = new Producto();

        int filaSelect = jTablePos.getSelectedRow();
        if (filaSelect >= 0) {
            //cadena_total = modelo.getValueAt(filaSelect, 3).toString();
            var_consulta = modelo.getValueAt(filaSelect, 0).toString();
            producto = productodb.consultar(var_consulta);
            rendimiento.setIngreso(rendimiento.getIngreso() - (Integer.valueOf(modelo.getValueAt(filaSelect, 2).toString()) * producto.getGanancia()));
            rendimiento.setImpuesto(rendimiento.getImpuesto() - (Integer.valueOf(modelo.getValueAt(filaSelect, 2).toString()) * producto.getIva()));
            rendimiento.setVenta(rendimiento.getVenta() - (Integer.valueOf(modelo.getValueAt(filaSelect, 2).toString()) * (producto.getPrecio())));
            //suma_total -= Integer.valueOf(cadena_total);
            suma_total -= (Integer.valueOf(modelo.getValueAt(filaSelect, 2).toString()) * (producto.getPrecio()));
            jTextFieldTot.setText(String.valueOf(suma_total));
            modelo.removeRow(filaSelect);

        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Fila no seleccionada");
        }

        jTextFieldCod.requestFocus();
    }//GEN-LAST:event_jButtonEliActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        /*JFrameMenu menu = new JFrameMenu();
         menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE );
         menu.setVisible(true);
         */

    }//GEN-LAST:event_formWindowClosing

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jTextFieldCodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodKeyReleased
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {

            var_consulta = jTextFieldCod.getText();
            producto = new Producto();
            //rendimiento = new Rendimiento();
            if (jTextFieldCod.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Falta valor de Codigo");
            } else {
                try {

                    producto = productodb.consultar(var_consulta);
                    if (producto.getId() == "") {
                        JOptionPane.showMessageDialog(null, "Producto no registrado");
//                        jfrmagregar.setVisible(true);
                    } else {
                        registry_count = modelo.getRowCount();
                        rendimiento.setIngreso(rendimiento.getIngreso() + (Integer.valueOf(jTextFieldCan.getText())) * producto.getGanancia());
                        rendimiento.setImpuesto(rendimiento.getImpuesto() + (Integer.valueOf(jTextFieldCan.getText())) * producto.getIva());
                        rendimiento.setVenta(rendimiento.getVenta() + (Integer.valueOf(jTextFieldCan.getText())) *producto.getPrecio());

                        datos[0] = producto.getId();
                        datos[1] = producto.getNombre();
                        datos[2] = jTextFieldCan.getText();

                        double_copy = Double.parseDouble(jTextFieldCan.getText()) * producto.getPrecio();
                        str_copy = String.format("%.02f",double_copy);
                        datos[3] = str_copy;
                        modelo.addRow(datos);
                        //cadena_total += Integer.toString(registry_count);
                        cadena_total = modelo.getValueAt(registry_count, 3).toString();
                        suma_total += Double.valueOf(cadena_total);
                        jTextFieldTot.setText(String.format("%.02f",suma_total));
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error " + e);
                }
            }
            jTextFieldCod.setText("");
            jTextFieldCan.setText("1");
            jTextFieldCod.requestFocus();

        }


    }//GEN-LAST:event_jTextFieldCodKeyReleased

    private void btn_nueva_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nueva_ventaActionPerformed
        // TODO add your handling code here:
        nuevaVenta();

    }//GEN-LAST:event_btn_nueva_ventaActionPerformed

    private void btnEliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVentaActionPerformed
        // TODO add your handling code here:

        while (modelo.getRowCount() > 0) {

            modelo.removeRow(0);
        }
        rendimiento = new Rendimiento();

        suma_total = 0;
        jTextFieldTot.setText("");
        jTextFieldCod.requestFocus();

    }//GEN-LAST:event_btnEliminarVentaActionPerformed

    private void jbtn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_imprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_imprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarVenta;
    private javax.swing.JButton btn_nueva_venta;
    private javax.swing.JButton jButtonAgr;
    private javax.swing.JButton jButtonEli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePos;
    private javax.swing.JTextField jTextFieldCan;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldTot;
    private javax.swing.JButton jbtn_imprimir;
    // End of variables declaration//GEN-END:variables
}
