/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.pos.adm;

import be.pos.adm.dat.UsuarioDB;
import be.pos.adm.ent.Usuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class JFrameAutentificacion extends javax.swing.JFrame {

    Usuario usuario;
    String str_copy;
    boolean bool;
    UsuarioDB usuariodb;
    JFrameAdministracion jfrm_administracion;
    char[] char_copy;

    public JFrameAutentificacion() {

        initComponents();
        char_copy = new char[20];
        str_copy = "";
        bool = false;
        usuario = new Usuario();
        usuariodb = new UsuarioDB();
        jfrm_administracion = new JFrameAdministracion();
        jfrm_administracion.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpassf_autentificar = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("    Clave de Administrador");

        jpassf_autentificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpassf_autentificarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jpassf_autentificar))
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpassf_autentificar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpassf_autentificarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpassf_autentificarKeyReleased
        // TODO add your handling code here:
        bool = false;
        jpassf_autentificar.requestFocus();
        if (evt.getKeyCode() == evt.VK_ENTER) {
            str_copy = String.copyValueOf(jpassf_autentificar.getPassword());
            bool = usuariodb.autentificar(str_copy);
            if (bool) {
                jfrm_administracion.setVisible(true);
                this.setVisible(false);
            } 
            else {
                jpassf_autentificar.setText("");
                jpassf_autentificar.requestFocus();
                JOptionPane.showMessageDialog(null, "Ingreso no autorizado");
            }
        }
    }//GEN-LAST:event_jpassf_autentificarKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jpassf_autentificar;
    // End of variables declaration//GEN-END:variables
}
